### PR TITLE
Fixes #250

### LINKED ISSUE #250: [BUG] Oak Planks Panel (Variant: Porthole) has missing texture
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.561-BETA

### Structurize Version

structurize-1.20.1-1.0.725-BETA

### Related Mods and their Versions

domum_ornamentum-1.20.1-1.0.184-BETA-universal

### Current Behavior

image
There's an edge with the purple texture. This is true when placed in other orientations and materials as well. 

image

### Expected Behavior

Pretty blocks!

### Reproduction Steps

Make the porthole variation of panels. Place it somewhere.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #350: Creates Blocks in DO
I'm using a datapack so the Architect's cutter can read and creates blocks using limestone, but nothing happens. Minecraft can read the data pack (datapack list green). I dont know what am I doing wrong, is there any other way like a mod that allows compatibility with the Create Mod building materials, like Veridium or Limestone?

### PR DESCRIPTION
**Pull request by Meisterfuchs**
Fixes https://github.com/ldtteam/Domum-Ornamentum/issues/250, this just adds the base block texture where a missing texture was before.

### CODE REVIEW

**Comment by Thodor12** [comment]
Write "Fixes #250" in your top comment to enable auto issue resolving

Can you sign the CLA?

**Comment by Meisterfuchs** [comment]
I have signed the CLA, I'm not sure why there are two comments from the bot.

But either Link to the CLA tells me I have agreed to it.

**Comment by Thodor12** [comment]
I'll take a look a bit later, currently in the train

**Review by Thodor12 — APPROVED** [review]
Thanks for taking the effort for fixing this

**Pull request merged**
