### PR TITLE
Resolve merge issues

### PR DESCRIPTION
**Pull request by Nightenom**

### CODE REVIEW

**Review by marchermans — CHANGES_REQUESTED** [review]
Material texture data is not supposed to be null! Architecturaly this change is a bad idea and the pr is not given a reason why this needs to change.

**Comment by Nightenom** [comment]
> Material texture data is not supposed to be null! Architecturaly this change is a bad idea and the pr is not given a reason why this needs to change.

It cant be null, the compound can be null if it's not present but any textureData will be EMPTY as designed by you, it's just macro for pulling from item stack, can be moved, but its logically tightened to texture data

**Comment by marchermans** [comment]
> > Material texture data is not supposed to be null! Architecturaly this change is a bad idea and the pr is not given a reason why this needs to change.
> 
> It cant be null, the compound can be null if it's not present but any textureData will be EMPTY as designed by you, it's just macro for pulling from item stack, can be moved, but its logically tightened to texture data

The code in this pr clearly returns null inseveral situations and code paths..... So it can be null. Please justify the changed code behaviour

**Comment by Nightenom** [comment]
> > > Material texture data is not supposed to be null! Architecturaly this change is a bad idea and the pr is not given a reason why this needs to change.
> > 
> > 
> > It cant be null, the compound can be null if it's not present but any textureData will be EMPTY as designed by you, it's just macro for pulling from item stack, can be moved, but its logically tightened to texture data
> 
> The code in this pr clearly returns null inseveral situations and code paths..... So it can be null. Please justify the changed code behaviour

No? - MaterialTextureData can't be null in any code path modified by this or both previous PRs (at least not intentionally.., If you still have issue with something please comment on code or specify the method name)
Method `CompoundTag extractNbtFromItemStack` returns null but it also does not create nor anyhow work with instance of MaterialTextureData, reason for this is to check whether the data even exists, else normal write/read methods can be used (remember compoundTag methods are getOrCreate-like)
Method `MaterialTextureData deserializeFromItemStack`, which uses the method above, uses deserialization method which can handle null as input returning EMPTY instance

**Review by marchermans — CHANGES_REQUESTED** [review]
Okey misread the code on the previous pass.

What exactly is this trying to achieve.
DO never supported merging. And it never intended to do so.

**Pull request merged**
