### PR TITLE
Fix fancy_light_spec.json

### PR DESCRIPTION
**Pull request by glorantq**
This commit fixes the broken texture references in the model of the fancy framed light

### CODE REVIEW

**Comment by Thodor12** [comment]
Can you show any relevant errors, before and afters? There has to be some reason to make this.

**Comment by glorantq** [comment]
No logs, I found this issue while rendering blocks with a third party tool. The reason to make this is that this file is not correct. While the game functions fine with the # missing, it should be there for texture references, just like it is there with all the other models.

**Comment by Thodor12** [comment]
Need verification it still works in-game in that case. We don't base code around any random third party tool, the important part is that it works in game.

**Comment by Raycoms** [comment]
Just a quick screenshot with your changes would be enough already

**Comment by glorantq** [comment]
It does work in game.
image

**Review by Raycoms — APPROVED** [review]

**Review by Thodor12 — APPROVED** [review]

**Pull request merged**
